// app.js
import './js/clock.js';
import './js/theme.js';
import './js/terminal.js';
import './js/github.js';
import './js/steam.js';
import './js/discord.js';
import './js/carousel.js';
import './js/fastfetch.js';